### ISSUE TITLE
Ajax call trouble in the Front end and routing problem

### ISSUE THREAD

**Issue by akhilpandey95** [AkhilHector/bucket#4]
Apparently there is no communication in between the front end react application and the Express Server.

**Comment by akhilpandey95** [comment]
@Ethcelon @abhijith-gururaj @saiteja55 i rolled back the commits now the HEAD is at the previous state so apart from that @Ethcelon please enlighten where is the trouble we are having with the react application because i think i have found a solution

**Comment by abhijith-gururaj** [comment]
I say we try adding form tag around the base rendering element and add the method to it. Also Adding the onSubmit handler to it. What say?

**Comment by akhilpandey95** [comment]
@Ethcelon can you send the PR regarding the ajax call or can i look up into the matter ?

**Comment by saiteja55** [comment]
@AkhilHector Is that problem resolved?

**Comment by akhilpandey95** [comment]
It will be resolved @Ethcelon said he would be looking up to the issue so i did not bother much

**Comment by akhilpandey95** [comment]
@Ethcelon dude are you into this or not ? :dash:

**Comment by akhilpandey95** [comment]
@Ethcelon There are some changes that i have made but not pushed yet so please be patient for one more day and expect the latest commit by tomorrow evening.

**Comment by akhilpandey95** [comment]
solved !!
